FROM node:11.6.0-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

RUN npm install react-scripts@2.1.2 -g --silent

COPY package.json /usr/src/app/package.json
RUN npm install

CMD ["npm", "start"]