version: '3.7'

services:
  nginx:
    build:
      context: ./back/docker/nginx
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    restart: always
    depends_on:
      - back

  back:
    env_file: .env
    image: back
    build:
      context: ./back
      dockerfile: docker/back/Dockerfile-dev
    command: "poetry run flask run --host=0.0.0.0 --port ${APP_PORT}"
    volumes:
      - "./back:/home/app/back"
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis

  db:
    env_file: .env
    build:
      context: ./back
      dockerfile: docker/db/Dockerfile
      args:
        - POSTGRES_DB_TEST

  redis:
    env_file: .env
    image: redis:5.0.5-alpine
