GOOGLE_PLACES_BASE_URL = "https://maps.googleapis.com/maps/api/place"
GOOGLE_PLACES_API_SUCCESS_STATUS = "OK"
GOOGLE_PLACES_API_ZERO_RESULTS = "ZERO_RESULTS"
GOOGLE_PLACES_OK_STATUSES = [GOOGLE_PLACES_API_SUCCESS_STATUS, GOOGLE_PLACES_API_ZERO_RESULTS]

NEARBY_DIRECTORY = "nearbysearch"
GOOGLE_PLACES_NEARBY_URL = "{}/{}".format(GOOGLE_PLACES_BASE_URL, NEARBY_DIRECTORY)

PLACE_DETAILS_DIRECTORY = "details"
PLACE_DETAILS_FIELDS = "adr_address,formatted_address,geometry,id,name,photo,place_id,type,url,vicinity"
GOOGLE_PLACE_DETAILS_URL = "{}/{}".format(GOOGLE_PLACES_BASE_URL, PLACE_DETAILS_DIRECTORY)

PLACE_PHOTO_DIRECTORY = "photo"
GOOGLE_PLACE_PHOTO_URL = "{}/{}".format(GOOGLE_PLACES_BASE_URL, PLACE_PHOTO_DIRECTORY)
