// FETCHING BACK API DATA
// --> LOGIN
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

// --> LOGOUT
export const USER_LOGOUT = "USER_LOGOUT"

// --> GENERAL USER MANAGEMENT
export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILED = "ADD_USER_FAILED"

export const USER_LOCATION_REQUESTED = "USER_LOCATION_REQUESTED"
export const USER_LOCATION_SUCCESS = "USER_LOCATION_SUCCESS"
export const USER_LOCATION_FAILED = "USER_LOCATION_FAILED"

// --> PLACES
export const FETCH_NEARBY_REQUESTED = "FETCH_NEARBY_REQUESTED"
export const FETCH_NEARBY_SUCCESS = "FETCH_NEARBY_SUCCESS"
export const FETCH_NEARBY_FAILED = "FETCH_NEARBY_FAILED"

export const ADD_LIKE_REQUESTED = "ADD_LIKE_REQUESTED"
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS"
export const ADD_LIKE_FAILED = "ADD_LIKE_FAILED"

export const ADD_DISLIKE_REQUESTED = "ADD_DISLIKE_REQUESTED"
export const ADD_DISLIKE_SUCCESS = "ADD_DISLIKE_SUCCESS"
export const ADD_DISLIKE_FAILED = "ADD_DISLIKE_FAILED"


// --> GENERIC ADD ENTITIES
export const ADD_ENTITIES = "ADD_ENTITIES"

// COMMON
export const STATUS = {REQUESTING: "REQUESTING", SUCCESS: "SUCCESS", FAILED: "FAILED"}