// FETCHING BACK API DATA
// --> LOGIN
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

// --> LOGOUT
export const USER_LOGOUT = "USER_LOGOUT"

// --> GENERAL USER MANAGEMENT
export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILED = "ADD_USER_FAILED"

// --> GENERIC ADD ENTITIES
export const ADD_ENTITIES = "ADD_ENTITIES"

// COMMON
export const STATUS = {REQUESTING: "REQUESTING", SUCCESS: "SUCCESS", FAILED: "FAILED"}